# Generated by Django 3.2.4 on 2022-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_master_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_m_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_state', models.CharField(blank=True, max_length=50, null=True)),
                ('student_city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
